### ISSUE TITLE
Add hostname white list to skip adding rel attributes

### ISSUE THREAD

**Issue by nickjj** [kenchan0130/jekyll-target-blank#10]
Hi,

#### The behavior I'm seeking is:

- All external links open in a new window
- All external links get noopner and noreferrer
- An optional white list of hostnames can be added which don't get the rel nofollow attributes (even if set)

#### Use case:

I'm going to be adding a site where 95% of the links are external and 5% of the links are trusted so I don't want to set nofollow.

#### Potential API for usage:

```yml
target-blank:
  rel_nofollow_skip_domains: ["example.com", "github.com"]
```

#### Example link output:

```
<a href="http://example.com" target="_blank">Example</a>
<a href="https://example.com" target="_blank">Example</a>
<a href="https://www.example.com" target="_blank">Example</a>
<a href="http://foo.github.com" target="_blank">GitHub</a>
<a href="https://www.github.com" target="_blank">GitHub</a>
<a href="https://foo.bar.github.com" target="_blank">GitHub</a>
<a href="https://somewhere.com" target="_blank" rel="nofollow">Somewhere</a>
```

**Comment by kenchan0130** [comment]
@nickjj 
Thank you for your contribution.
Looks good.

Since the head family seems to have started maintenance, I'm proposing whether it can be merged there.
https://github.com/keithmifsud/jekyll-target-blank/pull/35#issuecomment-541613706

Sorry for stopping the discussion.

**Comment by kenchan0130** [comment]
Hi @nickjj,
Since the maintainer of the head family has returned, I will close and move this issue.

**Comment by nickjj** [comment]
Thanks. In the end I found https://github.com/d-ogarkov/jekyll-extlinks which did the trick.
