### ISSUE TITLE
Unicode characters in URIs

### ISSUE THREAD

**Issue by mukrop** [kenchan0130/jekyll-target-blank#9]
* When processed URIs contain Unicode characters, the processing fails on `URI.parse` as it cannot handle non-acsii characters. The [documentation](https://www.rubydoc.info/stdlib/uri/URI.parse) suggests escaping the input string before parsing.
* The same bug is discussed in the original repository: keithmifsud/jekyll-target-blank#33
* MWE: A link to https://cs.wikipedia.org/wiki/Elektrárna_Chvaletice

As I managed to fix it locally by adding a call to `URI.escape`, I tried to file a pull request (#8). However, this method seems to be obsolete and the suggested `CGI.escape` causes multiple tests to fail.

As this is beyond my Ruby knowledge, I'm writing this up as an issue. Sorry, no PL in the end :-/.

**Comment by kenchan0130** [comment]
Hi @mukrop,
Since the maintainer of the head family has returned, I will close this issue.
https://github.com/keithmifsud/jekyll-target-blank/pull/35#issuecomment-542066735
